server:
  port: 50101 #服务端口

spring:
  cloud:
    config: false
  application:
    name: xc-govern-center #指定服务名
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: false #服务发现，是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://localhost:50101
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 600000 #服务注册表清理间隔（单位毫秒，默认是60*1000）

# actuator
info:
  author: pangzhao
  blog-url: http://localhost
  version: 1.2.3
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

