server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://192.168.8.6:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 192.168.8.6
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: D:/heima/video
  ffmpeg-path: E:/developServer/ffmpeg/bin/ffmpeg.exe