server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://172.168.20.134:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 172.168.20.134
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: F:/develop/video/
  ffmpeg-path: D:/Program Files/ffmpeg/bin/ffmpeg.exe